### ISSUE TITLE
Auto-add self recipient on init

### ISSUE THREAD

**Issue by andresriancho** [franela/vault#18]
When a user creates a new vault, add "self" as recipient. In other words, search the OS's keyring for a PGP key that has both public/private and add that user as recipient. If there is more than one key, show a warning and no-op.

Init should also have a `--no-self-add` (or similar) to prevent this behaviour.

**Comment by marcosnils** [comment]
We thought about this and we were wondering if there's a way in GPG to retrieve the current keyring owner or "self" user. As we couldn't find it back then we've decide to omit it. 

Do you know if this can be done?

**Comment by andresriancho** [comment]
Not sure if it can be done

**Comment by xetorthio** [comment]
I think you linked the wrong commit

**Comment by marcosnils** [comment]
Yup, I amended the commit but github doesn't realize about it :smile:
