### ISSUE TITLE
Tighten permissions for tempfile

### ISSUE THREAD

**Issue by andresriancho** [franela/vault#22]
A quick read of the source seems to indicate that in https://github.com/franela/vault/blob/master/gpg/gpg.go#L75 you guys create a temp file with 777? Maybe change that to more restricting perms to avoid other users reading sensitive info from them.

Potentially also vuln at https://github.com/franela/vault/blob/master/gpg/gpg.go#L101

**Comment by xetorthio** [comment]
Yes. I totally agree with you. We should have created it with `0600`

**Comment by andresriancho** [comment]
:+1:

**Comment by marcosnils** [comment]
@andresriancho agree. File permissions are too open. 

One clarification is that it's not a tempfile, that's the actual encrypted output file. So even though it's open to anyone the file is still encrypted :stuck_out_tongue_closed_eyes:

**Comment by marcosnils** [comment]
I've changed the permissions to 700 as GPG requires execution on the homedir also.
